// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *HomePage → Menu*
 */
export interface HomepageDocumentDataMenuItem {
  /**
   * Label field in *HomePage → Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Menu Label
   * - **API ID Path**: homepage.menu[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Menu ID field in *HomePage → Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Anchor link to the section in page
   * - **API ID Path**: homepage.menu[].menu_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_id: prismic.KeyTextField;
}

type HomepageDocumentDataSlicesSlice =
  | FooterSlice
  | ContactSlice
  | PhotoSlideshowSlice
  | TeaserSlice
  | NewsSlice
  | BannerSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * Logo field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Facebook link field in *HomePage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to Facebook page
   * - **API ID Path**: homepage.facebook_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook_link: prismic.LinkField;

  /**
   * AirBnB link field in *HomePage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to AirBnb page
   * - **API ID Path**: homepage.airbnb_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  airbnb_link: prismic.LinkField;

  /**
   * Menu field in *HomePage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.menu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu: prismic.GroupField<Simplify<HomepageDocumentDataMenuItem>>;

  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Item in *Banner → Default → Primary → Slide*
 */
export interface BannerSliceDefaultPrimarySlideItem {
  /**
   * Title field in *Banner → Default → Primary → Slide*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Slide title
   * - **API ID Path**: banner.default.primary.slide[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description 1 field in *Banner → Default → Primary → Slide*
   *
   * - **Field Type**: Text
   * - **Placeholder**: First description
   * - **API ID Path**: banner.default.primary.slide[].description_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description_1: prismic.KeyTextField;

  /**
   * Description 2 field in *Banner → Default → Primary → Slide*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Second description
   * - **API ID Path**: banner.default.primary.slide[].description_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description_2: prismic.KeyTextField;

  /**
   * Background image field in *Banner → Default → Primary → Slide*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.slide[].background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Button text field in *Banner → Default → Primary → Slide*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.slide[].button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button link field in *Banner → Default → Primary → Slide*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.slide[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * UUID field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section UUID
   * - **API ID Path**: banner.default.primary.uuid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uuid: prismic.KeyTextField;

  /**
   * Slide field in *Banner → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.slide[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  slide: prismic.GroupField<Simplify<BannerSliceDefaultPrimarySlideItem>>;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Item in *Contact → Default → Primary → Mail subjects*
 */
export interface ContactSliceDefaultPrimaryMailSubjectsItem {
  /**
   * Subject field in *Contact → Default → Primary → Mail subjects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Subject in the contact form
   * - **API ID Path**: contact.default.primary.mail_subjects[].subject
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subject: prismic.KeyTextField;
}

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * UUID field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section UUID
   * - **API ID Path**: contact.default.primary.uuid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uuid: prismic.KeyTextField;

  /**
   * Mail subjects field in *Contact → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.mail_subjects[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  mail_subjects: prismic.GroupField<
    Simplify<ContactSliceDefaultPrimaryMailSubjectsItem>
  >;

  /**
   * Google Maps URL field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.google_maps_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  google_maps_url: prismic.KeyTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Item in *Footer → Default → Primary → Information section*
 */
export interface FooterSliceDefaultPrimaryInformationSectionItem {
  /**
   * Title field in *Footer → Default → Primary → Information section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Information section title
   * - **API ID Path**: footer.default.primary.information_section[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Footer → Default → Primary → Information section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Information section description
   * - **API ID Path**: footer.default.primary.information_section[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *Footer → Default → Primary → Contact section*
 */
export interface FooterSliceDefaultPrimaryContactSectionItem {
  /**
   * Title field in *Footer → Default → Primary → Contact section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contact section title
   * - **API ID Path**: footer.default.primary.contact_section[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Mail address field in *Footer → Default → Primary → Contact section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.contact_section[].mail_address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mail_address: prismic.KeyTextField;

  /**
   * Phone number field in *Footer → Default → Primary → Contact section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.contact_section[].phone_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number: prismic.KeyTextField;
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * UUID field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section UUID
   * - **API ID Path**: footer.default.primary.uuid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uuid: prismic.KeyTextField;

  /**
   * Information section field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.information_section[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  information_section: prismic.GroupField<
    Simplify<FooterSliceDefaultPrimaryInformationSectionItem>
  >;

  /**
   * Contact section field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.contact_section[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contact_section: prismic.GroupField<
    Simplify<FooterSliceDefaultPrimaryContactSectionItem>
  >;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *News → Default → Primary*
 */
export interface NewsSliceDefaultPrimary {
  /**
   * UUID field in *News → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section UUID
   * - **API ID Path**: news.default.primary.uuid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uuid: prismic.KeyTextField;

  /**
   * Title field in *News → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: News title
   * - **API ID Path**: news.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Taggbox Widget ID field in *News → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.default.primary.taggbox_widget_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  taggbox_widget_id: prismic.KeyTextField;
}

/**
 * Default variation for News Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *News*
 */
type NewsSliceVariation = NewsSliceDefault;

/**
 * News Shared Slice
 *
 * - **API ID**: `news`
 * - **Description**: News
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsSlice = prismic.SharedSlice<"news", NewsSliceVariation>;

/**
 * Item in *PhotoSlideshow → Default → Primary → Photo*
 */
export interface PhotoSlideshowSliceDefaultPrimaryPhotoItem {
  /**
   * Image field in *PhotoSlideshow → Default → Primary → Photo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: photo_slideshow.default.primary.photo[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"426x320" | "426x282" | "426x593">;
}

/**
 * Primary content in *PhotoSlideshow → Default → Primary*
 */
export interface PhotoSlideshowSliceDefaultPrimary {
  /**
   * UUID field in *PhotoSlideshow → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section UUID
   * - **API ID Path**: photo_slideshow.default.primary.uuid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uuid: prismic.KeyTextField;

  /**
   * Title field in *PhotoSlideshow → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Photo Slideshow title
   * - **API ID Path**: photo_slideshow.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Photo field in *PhotoSlideshow → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: photo_slideshow.default.primary.photo[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  photo: prismic.GroupField<
    Simplify<PhotoSlideshowSliceDefaultPrimaryPhotoItem>
  >;
}

/**
 * Default variation for PhotoSlideshow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhotoSlideshowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PhotoSlideshowSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PhotoSlideshow*
 */
type PhotoSlideshowSliceVariation = PhotoSlideshowSliceDefault;

/**
 * PhotoSlideshow Shared Slice
 *
 * - **API ID**: `photo_slideshow`
 * - **Description**: PhotoSlideshow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhotoSlideshowSlice = prismic.SharedSlice<
  "photo_slideshow",
  PhotoSlideshowSliceVariation
>;

/**
 * Item in *Teaser → Default → Primary → Button*
 */
export interface TeaserSliceDefaultPrimaryButtonItem {
  /**
   * Label field in *Teaser → Default → Primary → Button*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teaser.default.primary.button[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Teaser → Default → Primary → Button*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: teaser.default.primary.button[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Teaser → Tarifs → Primary → Button*
 */
export interface TeaserSliceTarifsPrimaryButtonItem {
  /**
   * Label field in *Teaser → Tarifs → Primary → Button*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teaser.tarifs.primary.button[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Teaser → Tarifs → Primary → Button*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: teaser.tarifs.primary.button[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Teaser → Extras → Primary → Options*
 */
export interface TeaserSliceExtrasPrimaryOptionsItem {
  /**
   * Title field in *Teaser → Extras → Primary → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Option title
   * - **API ID Path**: teaser.extras.primary.options[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Teaser → Extras → Primary → Options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Option description
   * - **API ID Path**: teaser.extras.primary.options[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Teaser → Default → Primary*
 */
export interface TeaserSliceDefaultPrimary {
  /**
   * UUID field in *Teaser → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section ID
   * - **API ID Path**: teaser.default.primary.uuid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uuid: prismic.KeyTextField;

  /**
   * Title field in *Teaser → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Teaser title
   * - **API ID Path**: teaser.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Teaser → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Teaser Description
   * - **API ID Path**: teaser.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button field in *Teaser → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: teaser.default.primary.button[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  button: prismic.GroupField<Simplify<TeaserSliceDefaultPrimaryButtonItem>>;

  /**
   * Image field in *Teaser → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: teaser.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image alignment field in *Teaser → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: teaser.default.primary.image_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_alignment: prismic.SelectField<"left" | "right", "filled">;
}

/**
 * Default variation for Teaser Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeaserSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeaserSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Teaser → Tarifs → Primary*
 */
export interface TeaserSliceTarifsPrimary {
  /**
   * UUID field in *Teaser → Tarifs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section UUID
   * - **API ID Path**: teaser.tarifs.primary.uuid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uuid: prismic.KeyTextField;

  /**
   * Title field in *Teaser → Tarifs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Teaser title
   * - **API ID Path**: teaser.tarifs.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Teaser → Tarifs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Teaser Description
   * - **API ID Path**: teaser.tarifs.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button field in *Teaser → Tarifs → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: teaser.tarifs.primary.button[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  button: prismic.GroupField<Simplify<TeaserSliceTarifsPrimaryButtonItem>>;

  /**
   * Image field in *Teaser → Tarifs → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: teaser.tarifs.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image alignment field in *Teaser → Tarifs → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: teaser.tarifs.primary.image_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_alignment: prismic.SelectField<"left" | "right", "filled">;
}

/**
 * Tarifs variation for Teaser Slice
 *
 * - **API ID**: `tarifs`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeaserSliceTarifs = prismic.SharedSliceVariation<
  "tarifs",
  Simplify<TeaserSliceTarifsPrimary>,
  never
>;

/**
 * Primary content in *Teaser → Extras → Primary*
 */
export interface TeaserSliceExtrasPrimary {
  /**
   * UUID field in *Teaser → Extras → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section UUID
   * - **API ID Path**: teaser.extras.primary.uuid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uuid: prismic.KeyTextField;

  /**
   * Title field in *Teaser → Extras → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Teaser title
   * - **API ID Path**: teaser.extras.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Teaser → Extras → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Teaser Description
   * - **API ID Path**: teaser.extras.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Teaser → Extras → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: teaser.extras.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image alignment field in *Teaser → Extras → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: teaser.extras.primary.image_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_alignment: prismic.SelectField<"left" | "right", "filled">;

  /**
   * Options field in *Teaser → Extras → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: teaser.extras.primary.options[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  options: prismic.GroupField<Simplify<TeaserSliceExtrasPrimaryOptionsItem>>;
}

/**
 * Extras variation for Teaser Slice
 *
 * - **API ID**: `extras`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeaserSliceExtras = prismic.SharedSliceVariation<
  "extras",
  Simplify<TeaserSliceExtrasPrimary>,
  never
>;

/**
 * Slice variation for *Teaser*
 */
type TeaserSliceVariation =
  | TeaserSliceDefault
  | TeaserSliceTarifs
  | TeaserSliceExtras;

/**
 * Teaser Shared Slice
 *
 * - **API ID**: `teaser`
 * - **Description**: Teaser
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeaserSlice = prismic.SharedSlice<"teaser", TeaserSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataMenuItem,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimarySlideItem,
      BannerSliceDefaultPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimaryMailSubjectsItem,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimaryInformationSectionItem,
      FooterSliceDefaultPrimaryContactSectionItem,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      NewsSlice,
      NewsSliceDefaultPrimary,
      NewsSliceVariation,
      NewsSliceDefault,
      PhotoSlideshowSlice,
      PhotoSlideshowSliceDefaultPrimaryPhotoItem,
      PhotoSlideshowSliceDefaultPrimary,
      PhotoSlideshowSliceVariation,
      PhotoSlideshowSliceDefault,
      TeaserSlice,
      TeaserSliceDefaultPrimaryButtonItem,
      TeaserSliceDefaultPrimary,
      TeaserSliceTarifsPrimaryButtonItem,
      TeaserSliceTarifsPrimary,
      TeaserSliceExtrasPrimaryOptionsItem,
      TeaserSliceExtrasPrimary,
      TeaserSliceVariation,
      TeaserSliceDefault,
      TeaserSliceTarifs,
      TeaserSliceExtras,
    };
  }
}
