// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  contact: dynamic(() => import("./Contact")),
  footer: dynamic(() => import("./Footer")),
  news: dynamic(() => import("./News")),
  photo_slideshow: dynamic(() => import("./PhotoSlideshow")),
  teaser: dynamic(() => import("./Teaser")),
};
